[package]
name = "math-exps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cas-core = { path = "../cas-core" }
num = { version = "0.4.0" }
